### ISSUE TITLE
Add error message if `javac` or `kotlinc` are not found

### ISSUE THREAD

**Issue by arksap2002** [JetBrains-Research/TestSpark#320]
**Describe the bug**
In a situation where there is no compiler, the plugin does not show an error.

**Comment by Vladislav0Art** [comment]
> **Describe the bug** In a situation where there is no compiler, the plugin does not show an error.

This issue is important. 

If there is no Kotlin compiler in the `PATH`, the user will see an error about LLM not being able to generate compilable tests, which is wrong and misleading (a user cannot solve this error because he is not pointed at the right cause). As we discussed with @Frosendroska, there is no easy solution to locate the Kotlin compiler (unlike the Java compiler). Therefore, we decided to explicitly show an error that prompts users to set the kotlin compiler into `PATH`.
