### ISSUE TITLE
"Generation is already running" warning when a different project opened

### ISSUE THREAD

**Issue by Vladislav0Art** [JetBrains-Research/TestSpark#390]
**Describe the bug**
I ran TestSpark on a project A and received a test suite in the sidebar (I did not delete the sidebar). I closed the current project via pressing 'X' button on a mac window (notice that I did not close the IDE but a project within the same IDE instance!). I opened a different project and received the following warning:

<img width="606" alt="Screenshot 2024-10-11 at 16 28 26" src="https://github.com/user-attachments/assets/f620b85f-a3f2-4d03-98dc-32e9e5d027cf">

This warning neither allows me to execute any subsequent generations nor does it terminate the previous generation if I click "Terminate". It is sort of **soft deadlock**. I can only re-open the IDE to fix this.

**To Reproduce**
1. Open a project A;
2. Generate tests and do not close the sidebar (idk whether it matters);
3. Close the project A;
4. Open a project B (A != B);
5. Attempt to generate tests in project B -> warning occurred -> try to terminate -> no-op -> soft deadlock.

**Expected behavior**
No soft deadlocks.

**Comment by pderakhshanfar** [comment]
The terminate button basically does nothing:
![image](https://github.com/user-attachments/assets/748f6a0a-bf35-472f-abc7-12e1f9df75cf)
We just have a boolean value and we never keep track of the process. Se. we can either make the `isRunning` flag false again orrefactor how termination and process monitoring work

**Comment by Vladislav0Art** [comment]
> perform a major refactoring how termination and process monitoring work

I recommend trying to find a suitable solution that is least workload-demanding so as not to delay the release and create an issue for a major refactor "sometime later" after the release.

@pderakhshanfar what do you think?

**Comment by pderakhshanfar** [comment]
@Vladislav0Art I think I found an "acceptable" solution without major refactoring. In summary, with the more advanced indicator management that we have developed when extracting `core` module, can be very helpful here. So, we can actually check the indicator in the `TestGenerationController` instead of `isRunning` flag. Also, terminate can trigger the `cancel()` method from the indicator.  I have made a PR [here](https://github.com/JetBrains-Research/TestSpark/pull/393) with this solution.
